name: 检测m3u8是否有效

on:
  schedule:
    - cron: '0 22 * * *'  # 每天 UTC 时间 1:00 执行，即北京时间 9:00

  workflow_dispatch:  # 手动触发

jobs:
  check_m3u8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装扩展库
        run: pip install aiohttp

      - name: 运行脚本
        run: |
          python iptv/check_m3u8.py

      - name: 缓存运行结果
        uses: actions/upload-artifact@v4
        with:
          name: cache
          path: $GITHUB_WORKSPACE/iptv/
          
      - name: 提交更新
        run: |
          cd $GITHUB_WORKSPACE/iptv/
          ls
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update proxy_m3u8"
          git push
